# This is the base OS  #dockerfile reference --> reference
FROM almalinux:9 
RUN dnf install nginx -y
LABEL project="expense" \
      environment="dev" \
      component="frontend" \
      author="vinod" 
