# This is the base OS  #dockerfile reference --> reference
FROM almalinux:9 
RUN dnf install nginx -y
# nginx command to start in container --> docker community forums
CMD  ["nginx", "-g", "daemon off;"]